app = "ourphotos-backend"
primary_region = "ams"  # Bu bölgeyi ihtiyacınıza göre değiştirebilirsiniz

[build]
  # Dockerfile kullandığınız için builder özelleştirmeye gerek yok

[env]
  PORT = "8080"
  # Diğer environment değişkenlerini ekleyebilirsiniz
  # Önemli: Hassas bilgileri buraya koymayın, bunları 'fly secrets set' ile ayarlayın

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024